<div class="schedule-wrapper"><header class="days-buttons"><button class="active"><time datetime="2014-03-19"><span>Mercredi 19 mars</span></time></button><button><time datetime="2014-03-20"><span>Jeudi 20 mars</span></time></button><button><time datetime="2014-03-21"><span>Vendredi 21 mars</span></time></button><button></button></header><div class="js-slider"><div class="js-slider-container"><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">10:00<span class="time-slot-end"> à 11:15</span></td><td></td><td></td><td></td><td></td>
				<td class="session no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/test-jours-1/">Test jours -1</a></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr></tbody></table></div><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">7:15<span class="time-slot-end"> à 8:30</span></td>
				<td class="session break no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/dejeuner/">Déjeuner</a></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">8:30<span class="time-slot-end"> à 10:00</span></td>
				<td class="session keynote grand-hall speaker-thumb" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/beyond-mobile-where-no-geek-has-gone-before/">Beyond mobile: where no geek has gone before</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Josh Clark</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T08:30:00+00:00">8:30</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T10:00:00+00:00">10:00</time></span></span></div></div><span class="session-speaker-thumb"><!-- position: absolute --><img src="http://waq2014.job.paulcote.net/wp-content/uploads/2013/10/clark-187x160.png" itemprop="image"></span><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td>
				<td class="session break small no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/pause-cafe/">Pause-café</a></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:30<span class="time-slot-end"> à 12:00</span></td>
				<td class="session salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/travailler-a-distance-pour-une-entreprise-non-quebecoise/">Travailler à distance pour une entreprise non-québécoise</a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session medias-sociaux salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/photographie-avoir-de-belles-photos-sur-son-site-web-sans-se-faire-poursuivre/">Photographie: avoir de belles photos sur son site web sans se faire poursuivre</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Francis Vachon</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/transformez-les-donnees-en-dollars-avec-le-big-data/">Transformez les données en dollars avec le "big data" !</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/innovation-web-et-nouvelles-formes-de-recits/">Innovation web et nouvelles formes de récits</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">11:15<span class="time-slot-end"> à 12:00</span></td>
				<td class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/open-data-oui-mais-comment/">Open data : oui, mais comment?</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Jean-Philippe Boily</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/reussir-la-mise-en-place-dun-intranet-pas-si-facile-avec-les-outils-du-web/">Réussir la mise en place d’un intranet : pas si facile avec les outils du web!</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/la-ludification-le-nouvel-outil-marketing/">La ludification, le nouvel outil marketing</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">12:00<span class="time-slot-end"> à 13:15</span></td>
				<td class="session break no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/diner/">Dîner</a></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 14:45</span></td>
				<td class="session salle-libeo no-speaker" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/villes-intelligentes-et-cultures-numeriques/">Villes intelligentes et cultures numériques</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-ixmedia no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/gerer-le-site-web-dune-grande-organisation-decentralisee-oui-cest-possible/">Gérer le site Web d'une grande organisation décentralisée : oui c'est possible!</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/anticiper-et-gerer-les-crises-sur-les-medias-sociaux/">Anticiper et gérer les crises sur les médias sociaux</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/la-mobilite-et-nous/">La mobilité et nous</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:00<span class="time-slot-end"> à 14:45</span></td>
				<td class="session salle-ixmedia no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/resultats-de-recherche-ameliores-avec-les-microdonnees-html5/">Résultats de recherche améliorés avec les microdonnées HTML5</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/sound-design-et-internet-strategie-et-avant-garde/">Sound design et internet: stratégie et avant-garde</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/experience-client-comment-humaniser-le-web-et-toucher-vos-clients/">Expérience client : Comment humaniser le web et toucher vos clients ?</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:45<span class="time-slot-end"> à 15:30</span></td><td></td>
				<td class="session salle-ixmedia no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/moi-com-recit-dune-vie-en-ligne/">Moi.com : récit d’une vie en ligne</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/les-outils-du-e-learning-sont-ils-sous-estimes-par-la-communaute-du-web/">Les outils du E-Learning sont-ils sous-estimés par la communauté du Web?</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/responsive-au-dela-du-buzzword/">Responsive: Au-delà du buzzword</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td></tr><tr><td class="time-slot">15:30<span class="time-slot-end"> à 15:45</span></td>
				<td class="session break small no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/pause-cafe-2/">Pause-café</a></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:45<span class="time-slot-end"> à 16:30</span></td>
				<td class="session salle-libeo no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/museomix-remixer-le-musee-a-lheure-du-numerique/">Museomix : remixer le musée à l’heure du numérique</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-ixmedia no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/pivoting-digital-businesses-new-established/">Pivoting Digital Businesses: New &amp; Established</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/10-ans-danalytique-en-40-minutes-secrets-dun-veteran/">10 ans d'analytique en 40 minutes: secrets d'un vétéran</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/developpement-web-dentreprise-degraisse-architecture-orientee-web-et-mort-aux-services-ws/">Développement Web d'entreprise dégraissé : Architecture orientée Web et mort aux services WS-*</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td></tr><tr><td class="time-slot">16:30<span class="time-slot-end"> à 17:15</span></td>
				<td class="session salle-libeo no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/bordeaux-ville-numerique/">Bordeaux, ville numérique</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-ixmedia no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/comment-rediger-ou-repondre-a-un-appel-doffres-web/">Comment rédiger ou répondre à un appel d’offres web</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/le-developpement-web-avec-google-chrome/">Le développement web avec Google Chrome</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td class="session salle-deloitte no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/comment-utiliser-les-reseaux-sociaux-pour-optimiser-la-visibilite-de-son-site-web-sur-google/">Comment utiliser les réseaux sociaux pour optimiser la visibilité de son site web sur Google</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td></tr><tr><td class="time-slot">17:15<span class="time-slot-end"> à 19:00</span></td>
				<td class="session keynote grand-hall no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/5-a-7/">5 à 7</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T17:15:00+00:00">17:15</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T19:00:00+00:00">19:00</time></span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr></tbody></table></div><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td><td></td><td></td>
				<td class="session salle-bell no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.job.paulcote.net/sessions/test-jour-2/">Test jour 2</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td><td></td></tr></tbody></table></div><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr class="no-sessions"><td class="time-slot"></td></tr></tbody></table></div></div></div></div>