<div class="schedule-wrapper"><header class="days-buttons"><button class="active"><time datetime="2014-03-19"><span>mercredi 19 mars</span></time></button><button><time datetime="2014-03-20"><span>jeudi 20 mars</span></time></button><button><time datetime="2014-03-21"><span>vendredi 21 mars</span></time></button></header><div class="js-slider"><div class="js-slider-container"><div class="day-wrapper slide" style="left: 0px;"><table class="grid"><thead><tr><th class="column-time-slot" style="left: 0px;"></th><th class="column_salle-libeo" style="left: 0px;">Salle Libéo</th><th class="column_salle-ixmedia" style="left: 0px;">Salle iXmédia</th><th class="column_salle-bell" style="left: 0px;">Salle Bell</th><th class="column_salle-deloitte" style="left: 0px;">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">8:30<span class="time-slot-end"> à 11:45</span></td>
				<td data-session-id="469" class="session salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=html5-windows-8-amis-avec-benefices">HTML5 &amp; Windows 8: amis avec bénéfices</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Frédéric Harper</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td><td></td><td></td></tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 16:30</span></td>
				<td data-session-id="471" class="session salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=html5-windows-8-amis-avec-benefices-2">HTML5 &amp; Windows 8: amis avec bénéfices</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Frédéric Harper</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td><td></td><td></td></tr><tr class="no-sessions"><td class="time-slot">16:30<span class="time-slot-end"> à 19:00</span></td><td></td><td></td><td></td><td></td></tr><tr class="no-sessions"><td class="time-slot">19:00<span class="time-slot-end"> à 20:30</span></td><td></td><td></td><td></td><td></td></tr></tbody></table></div><div class="day-wrapper slide" style="left: 0px;"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">7:15<span class="time-slot-end"> à 8:30</span></td>
				<td data-session-id="473" class="session break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=dejeuner">Déjeuner</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">8:30<span class="time-slot-end"> à 10:00</span></td>
				<td data-session-id="475" class="session keynote grand-hall bookmarked speaker-thumb" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=beyond-mobile-where-no-geek-has-gone-before">Beyond mobile: where no geek has gone before </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Josh Clark</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T08:30:00+00:00">8:30</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T10:00:00+00:00">10:00</time></span></span></div></div><span class="session-speaker-thumb"><!-- position: absolute --><img src="http://waq2014.dev.libeo.com/wp-content/uploads/2013/12/clark.png"></span><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td>
				<td data-session-id="477" class="session break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=pause-cafe">Pause-café</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:30<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="479" class="session salle-libeo panel bookmarked" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=travailler-a-distance-pour-une-entreprise-non-quebecoise">Travailler à distance pour une entreprise non-québecoise</a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="481" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=photographie-avoir-de-belles-photos-sur-son-site-sans-se-faire-poursuivre">Photographie: Avoir de belles photos sur son site sans se faire poursuivre</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Francis Vachon</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="485" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=transformez-les-donnees-en-dollars-avec-le-big-data">Transformez les données en dollars avec le "Big Data"</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Philippe Nieuwbourg</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="489" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=innovation-web-et-nouvelles-formes-de-recits">Innovation web et nouvelles formes de récits</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Xavier K. Richard</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">11:15<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="483" class="session salle-ixmedia bookmarked" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=open-data-oui-mais-comment">Open Data : Oui, mais comment?</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Sam Vermette</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="487" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=reussir-la-mise-en-place-dun-intranet-pas-si-facile-avec-les-outils-du-web">Réussir la mise en place d’un intranet : pas si facile avec les outils du web</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Yann Sadok</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="491" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=la-ludification-le-nouvel-outil-marketing">La ludification, le nouvel outil marketing</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Nicolas Babin</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">12:00<span class="time-slot-end"> à 13:15</span></td>
				<td data-session-id="495" class="session break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=diner">Dîner</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 14:00</span></td>
				<td data-session-id="493" class="session salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=villes-intelligentes-et-cultures-numeriques">Villes intelligentes et cultures numériques</a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="499" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=gerer-le-site-web-dune-grande-organisation-decentralisee">Gérer le site Web d'une grande organisation décentralisée</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="507" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=anticiper-et-gerer-les-crises-sur-les-medias-sociaux">Anticiper et gérer les crises sur les médias sociaux</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="513" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=la-mobilite-et-nous">La mobilité et nous</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:00<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="503" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=resultats-de-recherche-ameliores-avec-les-microdonnees-html5">Résultats de recherche améliorés avec les microdonnées HTML5</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="509" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=sound-design-et-internet-strategie-et-avant-garde">Sound design et internet: stratégie et avant-garde</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="515" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=experience-client-comment-humaniser-le-web-et-touche-vos-clients">Expérience client : Comment humaniser le web et touche vos clients</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:45<span class="time-slot-end"> à 15:30</span></td>
				<td data-session-id="497" class="session salle-libeo panel" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=des-lieux-pour-creer-le-web">Des lieux pour créer le Web </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="505" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=moi-com-recit-dune-vie-en-ligne">Moi.com : récit d’une vie en ligne </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="511" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=les-outils-du-e-learning-sont-ils-sous-estimes-par-la-communaute-du-web">Les outils du E-Learning sont-ils sous-estimés par la communauté du Web?</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="517" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=responsive-au-dela-du-buzzword">Responsive: Au-delà du buzzword</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:30<span class="time-slot-end"> à 15:45</span></td>
				<td data-session-id="519" class="session break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=pause-cafe-2">Pause-café</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:45<span class="time-slot-end"> à 16:30</span></td>
				<td data-session-id="521" class="session salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=museomix-remixer-le-musee-a-lheure-du-numerique">Museomix : remixer le musée à l’heure du numérique</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="525" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=pivoting-digital-businesses-new-established">Pivoting Digital Businesses: New &amp; Established </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="529" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=10-ans-danalytique-en-40-minutes-secrets-dun-veteran">10 ans d'analytique en 40 minutes: secrets d'un vétéran</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="533" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=developpement-web-dentreprise-degraisse-architecture-orientee-web-et-mort-aux-services-ws">Développement Web d'entreprise dégraissé : Architecture orientée Web et mort aux services WS-*</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">16:30<span class="time-slot-end"> à 17:15</span></td>
				<td data-session-id="523" class="session salle-libeo no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=bordeaux-ville-numerique">Bordeaux, ville numérique</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="527" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=comment-rediger-ou-repondre-a-un-appel-doffres-web">Comment rédiger ou répondre à un appel d’offres web</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="531" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=le-developpement-web-avec-google-chrome">Le développement web avec Google Chrome</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="535" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=comment-utiliser-les-reseaux-sociaux-pour-optimiser-la-visibilite-de-son-site-web-sur-google">Comment utiliser les réseaux sociaux pour optimiser la visibilité de son site web sur Google</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">17:15<span class="time-slot-end"> à 19:00</span></td>
				<td data-session-id="537" class="session keynote grand-hall no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=speed-consulting">Speed consulting</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T17:15:00+00:00">17:15</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T19:00:00+00:00">19:00</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr></tbody></table></div><div class="day-wrapper slide" style="left: 0px;"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">7:15<span class="time-slot-end"> à 8:30</span></td>
				<td data-session-id="539" class="session keynote grand-hall" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=dejeuner-lacces-a-linformation-a-lere-du-big-data">Déjeuner - L’accès à l’information à l’ère du Big Data</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-21T07:15:00+00:00">7:15</time></span> à <span><time itemprop="endDate" datetime="2014-03-21T08:30:00+00:00">8:30</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">8:30<span class="time-slot-end"> à 10:00</span></td>
				<td data-session-id="541" class="session keynote grand-hall no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=penser-lexperience-utilisateur-mobile">Penser l'expérience utilisateur mobile </a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-21T08:30:00+00:00">8:30</time></span> à <span><time itemprop="endDate" datetime="2014-03-21T10:00:00+00:00">10:00</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td>
				<td data-session-id="545" class="session break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=pause-cafe-3">Pause-café</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:30<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="543" class="session salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=financer-son-projet-dentreprise-web">Financer son projet d'entreprise web </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="547" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=les-mutations-affectant-lunivers-du-journalisme">Les mutations affectant l'univers du journalisme</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="551" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=architectures-du-21e-siecle">Architectures du 21e siècle </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td></td></tr><tr><td class="time-slot">11:15<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="549" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=leffet-cupcake-10-tendances-en-design-ux">L'effet Cupcake : 10 tendances en design UX </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="553" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=la-federation-didentite-applications-concretes-et-opportunites">La fédération d’identité – applications concrètes et opportunités </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="555" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=commerce-electronique-et-entreprises-quebecoises-la-reussite-est-telle-encore-possible">Commerce électronique et entreprises Québécoises, la réussite est telle encore possible.</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">12:00<span class="time-slot-end"> à 13:15</span></td>
				<td data-session-id="557" class="session break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=diner-2">Dîner</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="559" class="session salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=le-web-au-feminin">Le Web au féminin </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="561" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=les-synergies-entre-referencement-organique-et-referencement-payant">Les synergies entre référencement organique et référencement payant</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="565" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=cliquez-ici">Cliquez ici</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="569" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=introduction-au-big-data-avec-apache-hadoop">Introduction au Big Data avec Apache Hadoop </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:00<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="563" class="session salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=comment-evaluer-la-qualite-dun-site-selon-les-techniques-dintegration">Comment évaluer la qualité d’un site selon les techniques d'intégration</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="567" class="session salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=datavisualisation-scenariser-communiquer-et-monetiser-vos-donnees">Datavisualisation : scénariser, communiquer et monetiser vos données</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="571" class="session salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=start-up-vs-grande-entreprise-ce-quelles-peuvent-apprendre-lune-de-lautre">Start-up vs grande entreprise : ce qu’elles peuvent apprendre l'une de l'autre</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:45<span class="time-slot-end"> à 15:00</span></td>
				<td data-session-id="573" class="session break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=pause">Pause</a></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:00<span class="time-slot-end"> à 16:30</span></td>
				<td data-session-id="575" class="session keynote grand-hall" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/?session=css-grows-up">CSS Grows Up </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-21T15:00:00+00:00">15:00</time></span> à <span><time itemprop="endDate" datetime="2014-03-21T16:30:00+00:00">16:30</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr></tbody></table></div></div></div></div>