<div class="schedule-wrapper"><header class="days-buttons"><button><time datetime="2014-03-19"><span>mercredi 19 mars</span></time></button><button><time datetime="2014-03-20"><span>jeudi 20 mars</span></time></button><button><time datetime="2014-03-21"><span>vendredi 21 mars</span></time></button></header><div class="js-slider"><div class="js-slider-container"><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">8:30<span class="time-slot-end"> à 11:45</span></td>
				<td data-session-id="469" class="session filter-all salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/html5-windows-8-amis-avec-benefices/">HTML5 &amp; Windows 8: amis avec bénéfices</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Frédéric Harper</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td class="empty"></td><td class="empty"></td><td class="empty"></td></tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 16:30</span></td>
				<td data-session-id="471" class="session filter-all salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/html5-windows-8-amis-avec-benefices-2/">HTML5 &amp; Windows 8: amis avec bénéfices</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Frédéric Harper</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td class="empty"></td><td class="empty"></td><td class="empty"></td></tr><tr class="no-sessions"><td class="time-slot">16:30<span class="time-slot-end"> à 19:00</span></td><td class="empty"></td><td class="empty"></td><td class="empty"></td><td class="empty"></td></tr><tr class="no-sessions"><td class="time-slot">19:00<span class="time-slot-end"> à 20:30</span></td><td class="empty"></td><td class="empty"></td><td class="empty"></td><td class="empty"></td></tr></tbody></table></div><div class="day-wrapper slide active"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">7:15<span class="time-slot-end"> à 8:30</span></td>
				<td data-session-id="473" class="session filter-all break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Déjeuner</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">8:30<span class="time-slot-end"> à 10:00</span></td>
				<td data-session-id="475" class="session filter-all filter-analytics filter-contenu filter-design filter-entreprise filter-medias-sociaux filter-mobile filter-programmation filter-ux bookmarked keynote salle-grand-hall speaker-thumb" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/beyond-mobile-where-no-geek-has-gone-before/">Beyond mobile: where no geek has gone before</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Josh Clark</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T08:30:00+00:00">8:30</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T10:00:00+00:00">10:00</time></span></span></div></div><span class="session-speaker-thumb"><!-- position: absolute --><img src="http://waq2014.dev.libeo.com/wp-content/uploads/2013/12/clark.png"></span><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td>
				<td data-session-id="477" class="session filter-all break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Pause-café</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:30<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="479" class="session filter-all filter-analytics filter-design filter-ux salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/travailler-a-distance-pour-une-entreprise-non-quebecoise/">Travailler à distance pour une entreprise non-québecoise</a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="481" class="session filter-all filter-entreprise filter-programmation salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/photographie-avoir-de-belles-photos-sur-son-site-sans-se-faire-poursuivre/">Photographie: Avoir de belles photos sur son site sans se faire poursuivre</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Francis Vachon</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="485" class="session filter-all filter-design filter-mobile filter-programmation salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/transformez-les-donnees-en-dollars-avec-le-big-data/">Transformez les données en dollars avec le "Big Data"</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Philippe Nieuwbourg</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="489" class="session filter-all filter-medias-sociaux filter-programmation bookmarked salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/innovation-web-et-nouvelles-formes-de-recits/">Innovation web et nouvelles formes de récits</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Xavier K. Richard</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">11:15<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="483" class="session filter-all filter-contenu filter-medias-sociaux bookmarked salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/open-data-oui-mais-comment/">Open Data : Oui, mais comment?</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Sam Vermette</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="487" class="session filter-all filter-contenu filter-medias-sociaux filter-programmation bookmarked salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/reussir-la-mise-en-place-dun-intranet-pas-si-facile-avec-les-outils-du-web/">Réussir la mise en place d’un intranet : pas si facile avec les outils du web</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Yann Sadok</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="491" class="session filter-all filter-design filter-medias-sociaux filter-programmation salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/la-ludification-le-nouvel-outil-marketing/">La ludification, le nouvel outil marketing</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Nicolas Babin</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">12:00<span class="time-slot-end"> à 13:15</span></td>
				<td data-session-id="495" class="session filter-all break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Dîner</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 14:00</span></td>
				<td data-session-id="493" class="session filter-all filter-contenu filter-entreprise filter-programmation filter-ux salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/villes-intelligentes-et-cultures-numeriques/">Villes intelligentes et cultures numériques</a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="499" class="session filter-all filter-contenu filter-mobile filter-ux bookmarked salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/gerer-le-site-web-dune-grande-organisation-decentralisee/">Gérer le site Web d'une grande organisation décentralisée</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="507" class="session filter-all filter-design filter-mobile salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/anticiper-et-gerer-les-crises-sur-les-medias-sociaux/">Anticiper et gérer les crises sur les médias sociaux</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="513" class="session filter-all filter-contenu filter-mobile bookmarked salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/la-mobilite-et-nous/">La mobilité et nous</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:00<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="503" class="session filter-all filter-analytics filter-mobile filter-ux salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/resultats-de-recherche-ameliores-avec-les-microdonnees-html5/">Résultats de recherche améliorés avec les microdonnées HTML5</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="509" class="session filter-all filter-entreprise bookmarked salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/sound-design-et-internet-strategie-et-avant-garde/">Sound design et internet: stratégie et avant-garde</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="515" class="session filter-all filter-programmation filter-ux salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/experience-client-comment-humaniser-le-web-et-touche-vos-clients/">Expérience client : Comment humaniser le web et touche vos clients</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:45<span class="time-slot-end"> à 15:30</span></td>
				<td data-session-id="497" class="session filter-all filter-medias-sociaux filter-mobile salle-libeo panel" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/des-lieux-pour-creer-le-web/">Des lieux pour créer le Web </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="505" class="session filter-all filter-contenu filter-design salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/moi-com-recit-dune-vie-en-ligne/">Moi.com : récit d’une vie en ligne </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="511" class="session filter-all filter-contenu filter-design salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/les-outils-du-e-learning-sont-ils-sous-estimes-par-la-communaute-du-web/">Les outils du E-Learning sont-ils sous-estimés par la communauté du Web?</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="517" class="session filter-all filter-analytics filter-design bookmarked salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/responsive-au-dela-du-buzzword/">Responsive: Au-delà du buzzword</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:30<span class="time-slot-end"> à 15:45</span></td>
				<td data-session-id="519" class="session filter-all break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Pause-café</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">15:45<span class="time-slot-end"> à 16:30</span></td>
				<td data-session-id="521" class="session filter-all filter-entreprise filter-programmation salle-libeo" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/museomix-remixer-le-musee-a-lheure-du-numerique/">Museomix : remixer le musée à l’heure du numérique</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="525" class="session filter-all filter-contenu filter-entreprise filter-mobile bookmarked salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/pivoting-digital-businesses-new-established/">Pivoting Digital Businesses: New &amp; Established </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="529" class="session filter-all filter-medias-sociaux filter-ux salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/10-ans-danalytique-en-40-minutes-secrets-dun-veteran/">10 ans d'analytique en 40 minutes: secrets d'un vétéran</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="533" class="session filter-all filter-analytics filter-contenu filter-entreprise salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/developpement-web-dentreprise-degraisse-architecture-orientee-web-et-mort-aux-services-ws/">Développement Web d'entreprise dégraissé : Architecture orientée Web et mort aux services WS-*</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">16:30<span class="time-slot-end"> à 17:15</span></td>
				<td data-session-id="523" class="session filter-all filter-contenu filter-medias-sociaux filter-ux bookmarked salle-libeo no-speaker" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/bordeaux-ville-numerique/">Bordeaux, ville numérique</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="527" class="session filter-all filter-analytics filter-entreprise salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/comment-rediger-ou-repondre-a-un-appel-doffres-web/">Comment rédiger ou répondre à un appel d’offres web</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="531" class="session filter-all filter-design filter-mobile filter-ux salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/le-developpement-web-avec-google-chrome/">Le développement web avec Google Chrome</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="535" class="session filter-all filter-design filter-medias-sociaux salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/comment-utiliser-les-reseaux-sociaux-pour-optimiser-la-visibilite-de-son-site-web-sur-google/">Comment utiliser les réseaux sociaux pour optimiser la visibilité de son site web sur Google</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">17:15<span class="time-slot-end"> à 19:00</span></td>
				<td data-session-id="537" class="session filter-all filter-analytics filter-design filter-ux bookmarked keynote salle-grand-hall no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/speed-consulting/">Speed consulting</a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-20T17:15:00+00:00">17:15</time></span> à <span><time itemprop="endDate" datetime="2014-03-20T19:00:00+00:00">19:00</time></span></span></div></div><button class="session-bookmark remove"><span class="visuallyhidden">Retirer cette conférence à mon horaire</span></button></div></td>
			</tr></tbody></table></div><div class="day-wrapper slide"><table class="grid"><thead><tr><th class="column-time-slot"></th><th class="column_salle-libeo">Salle Libéo</th><th class="column_salle-ixmedia">Salle iXmédia</th><th class="column_salle-bell">Salle Bell</th><th class="column_salle-deloitte">Salle Deloitte</th></tr></thead><tbody><tr><td class="time-slot">7:15<span class="time-slot-end"> à 8:30</span></td>
				<td data-session-id="539" class="session filter-all keynote salle-grand-hall" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/dejeuner-lacces-a-linformation-a-lere-du-big-data/">Déjeuner - L’accès à l’information à l’ère du Big Data</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-21T07:15:00+00:00">7:15</time></span> à <span><time itemprop="endDate" datetime="2014-03-21T08:30:00+00:00">8:30</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">8:30<span class="time-slot-end"> à 10:00</span></td>
				<td data-session-id="541" class="session filter-all keynote salle-grand-hall no-speaker" colspan="4" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/penser-lexperience-utilisateur-mobile/">Penser l'expérience utilisateur mobile </a></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Grand Hall</span></span><span class="session-time-slot" itemprop="subEvent"><span><time itemprop="startDate" datetime="2014-03-21T08:30:00+00:00">8:30</time></span> à <span><time itemprop="endDate" datetime="2014-03-21T10:00:00+00:00">10:00</time></span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:00<span class="time-slot-end"> à 10:30</span></td>
				<td data-session-id="545" class="session filter-all break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Pause-café</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">10:30<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="543" class="session filter-all salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/financer-son-projet-dentreprise-web/">Financer son projet d'entreprise web </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="547" class="session filter-all salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/les-mutations-affectant-lunivers-du-journalisme/">Les mutations affectant l'univers du journalisme</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="551" class="session filter-all salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/architectures-du-21e-siecle/">Architectures du 21e siècle </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td class="empty"></td></tr><tr><td class="time-slot">11:15<span class="time-slot-end"> à 12:00</span></td>
				<td data-session-id="549" class="session filter-all salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/leffet-cupcake-10-tendances-en-design-ux/">L'effet Cupcake : 10 tendances en design UX </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="553" class="session filter-all salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/la-federation-didentite-applications-concretes-et-opportunites/">La fédération d’identité – applications concrètes et opportunités </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="555" class="session filter-all salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/commerce-electronique-et-entreprises-quebecoises-la-reussite-est-telle-encore-possible/">Commerce électronique et entreprises Québécoises, la réussite est telle encore possible.</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">12:00<span class="time-slot-end"> à 13:15</span></td>
				<td data-session-id="557" class="session filter-all break no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Dîner</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">13:15<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="559" class="session filter-all salle-libeo panel" rowspan="2" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/le-web-au-feminin/">Le Web au féminin </a></span><span class="session-description" itemprop="description">Panel</span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Libéo</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="561" class="session filter-all salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/les-synergies-entre-referencement-organique-et-referencement-payant/">Les synergies entre référencement organique et référencement payant</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="565" class="session filter-all salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/cliquez-ici/">Cliquez ici</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="569" class="session filter-all salle-deloitte" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/introduction-au-big-data-avec-apache-hadoop/">Introduction au Big Data avec Apache Hadoop </a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Deloitte</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr><td class="time-slot">14:00<span class="time-slot-end"> à 14:45</span></td>
				<td data-session-id="563" class="session filter-all salle-ixmedia" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/comment-evaluer-la-qualite-dun-site-selon-les-techniques-dintegration/">Comment évaluer la qualité d’un site selon les techniques d'intégration</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle iXmédia</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>

				<td data-session-id="567" class="session filter-all salle-bell" itemprop="subEvent" itemscope="" itemtype="http://schema.org/Event"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name"><a href="http://waq2014.dev.libeo.com/sessions/datavisualisation-scenariser-communiquer-et-monetiser-vos-donnees/">Datavisualisation : scénariser, communiquer et monetiser vos données</a></span><span class="session-speaker" itemprop="performer" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">Generic Speaker</span></span><span class="session-room" itemprop="location" itemscope="" itemtype="http://schema.org/Place"><span itemprop="name">Salle Bell</span></span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			<td class="empty"></td></tr><tr><td class="time-slot">14:45<span class="time-slot-end"> à 15:00</span></td>
				<td data-session-id="573" class="session filter-all break small no-speaker" colspan="4"><div class="session-wrapper"><!-- position: relative --><div class="session-content"><!-- table-cell -->
    	<div class="session-content-wrapper"><!-- position: relative --><span class="session-title" itemprop="name">Pause</span></div></div><button class="session-bookmark add"><span class="visuallyhidden">Ajouter cette conférence à mon horaire</span></button></div></td>
			</tr><tr class="no-sessions"><td class="time-slot">15:00<span class="time-slot-end"> à 16:30</span></td><td class="empty"></td><td class="empty"></td><td class="empty"></td><td class="empty"></td></tr></tbody></table></div></div></div></div>