var Slideshow=(function($,window,document,undefined){var defaultConfig={containerSelector:'.js-slider-container',slideSelector:'.slide',pageBtnSelector:'.button-page',arrowBtnSelector:'.button-nav',generateNavigation:true,navigationType:'page',pageBtnContainer:'.js-slider',arrowBtnContainer:'.js-slider',pageBtnContainerClass:'js-nav-pages',arrowBtnContainerClass:'js-nav-arrows',arrowBtnPreviousClass:'prev',arrowBtnNextClass:'next',};function Slideshow(obj,config,app){this.app=app;this.config=$.extend({},defaultConfig,config);this.slideshow=$(obj);this.container=this.slideshow.find(this.config.containerSelector);this.slides=this.slideshow.find(this.config.slideSelector);this.nbSlides=this.slides.length;this.slideWidth=this.slides.eq(0).outerWidth(true);this.pageButtons=this.slideshow.find('.blog-nav .button-page');this.arrowButtons=this.slideshow.find('.blog-nav .button.prev, .blog-nav .button.next');this.activePage=0;this.displayedSlides=3;this.init();}
Slideshow.prototype={init:function(){var self=this,fixLayout=false;self.changeSlide();if($(document).width()<1024){self.displayedSlides=1;fixLayout=true;}
$(window).resize(function(){self.slideWidth=self.slides.eq(0).outerWidth(true);self.container.width(self.slideWidth*self.nbSlides);self.slides.css('left',self.activePage*self.slideWidth*-self.displayedSlides);if($(document).width()<1024){self.displayedSlides=1;self.pageButtons.removeClass(WAQ.Constants.isActiveClass);if(!fixLayout){self.slides.css('left',0);self.activePage=0;self.arrowButtons.eq(0).hide();}
if(self.nbSlides>0){self.arrowButtons.eq(1).show();}
fixLayout=true;}
else{self.displayedSlides=3;if(fixLayout){self.slides.css('left',0);self.pageButtons.removeClass(WAQ.Constants.isActiveClass);self.activePage=0;}
fixLayout=false;}});self.arrowButtons.eq(0).hide();if(self.nbSlides<4){self.arrowButtons.eq(1).hide();}
self.pageButtons.eq(0).addClass(WAQ.Constants.isActiveClass);self.pageButtons.find('.pagecourante').remove();self.pageButtons.eq(0).append(' <span class="pagecourante visuallyhidden">Page courante</span>');self.container.width(self.slideWidth*self.nbSlides);self.slides.find('a, button').attr('tabindex','-1');self.slides.eq(self.displayedSlides*self.activePage).find('a, button').removeAttr('tabindex');self.slides.eq(self.displayedSlides*self.activePage).nextAll().slice(0,2).find('a, button').removeAttr('tabindex');},changeSlide:function(){var self=this;self.slideWidth=self.slides.eq(0).outerWidth(true);self.pageButtons.on('click',function(){$this=$(this);var index=$this.index()- 2,offset=self.slideWidth*index*-self.displayedSlides;self.activePage=index;self.slideWidth=self.slides.eq(0).outerWidth(true);offset=self.slideWidth*index*-self.displayedSlides;self.pageButtons.removeClass(WAQ.Constants.isActiveClass);$this.addClass(WAQ.Constants.isActiveClass);self.pageButtons.find('.pagecourante').remove();$this.append(' <span class="pagecourante visuallyhidden">Page courante</span>');if(index>0){self.arrowButtons.eq(0).show();}else{self.arrowButtons.eq(0).hide();}
if(index+ 1<self.pageButtons.length){self.arrowButtons.eq(1).show();}else{self.arrowButtons.eq(1).hide();}
self.slides.animate({left:offset},500);self.slides.find('a, button').attr('tabindex','-1');self.slides.eq(self.displayedSlides*self.activePage).find('a, button').removeAttr('tabindex');self.slides.eq(self.displayedSlides*self.activePage).nextAll().slice(0,2).find('a, button').removeAttr('tabindex');});self.arrowButtons.on('click',function(){var $this=$(this),activePage=self.activePage,newActivePage=activePage;if($this.hasClass('prev')){newActivePage--;}
else if($this.hasClass('next')){newActivePage++;}
self.activePage=newActivePage;self.slideWidth=self.slides.eq(0).outerWidth(true);offset=self.slideWidth*newActivePage*-self.displayedSlides;if(newActivePage>0){self.arrowButtons.eq(0).show();}else{self.arrowButtons.eq(0).hide();}
if(newActivePage+ 1<self.pageButtons.length){self.arrowButtons.eq(1).show();}else{self.arrowButtons.eq(1).hide();}
self.pageButtons.removeClass(WAQ.Constants.isActiveClass);self.pageButtons.eq(newActivePage).addClass(WAQ.Constants.isActiveClass);self.pageButtons.find('.pagecourante').remove();self.pageButtons.eq(newActivePage).append(' <span class="pagecourante visuallyhidden">Page courante</span>');self.slides.animate({left:offset},500);self.slides.find('a, button').attr('tabindex','-1');self.slides.eq(self.displayedSlides*self.activePage).find('a, button').removeAttr('tabindex');self.slides.eq(self.displayedSlides*self.activePage).nextAll().slice(0,2).find('a, button').removeAttr('tabindex');});}};return Slideshow;})(jQuery,window,document);